version: '3.7'
name: coinbase
services:
  proton:
    image: ghcr.io/timeplus-io/proton:latest
    pull_policy: always
    ports:
    - "3218:3218" # HTTP Streaming
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3218/proton/ping"]
      interval: 2s
      timeout: 10s
      retries: 3
      start_period: 10s

  benthos:
    image: jeffail/benthos:latest
    pull_policy: always
    command: streams
    ports:
    - "4195:4195"

  init-stream:
    image: ghcr.io/timeplus-io/proton:latest
    command:
      - sh
      - -c
      - |
        proton-client -h proton --query "CREATE STREAM IF NOT EXISTS tickers (best_ask decimal(10,2), best_ask_size decimal(10,8), best_bid decimal(10,2), best_bid_size decimal(10,8), high_24h decimal(10,2), last_size decimal(10,8), low_24h decimal(10,2), open_24h decimal(10,2), price decimal(10,2), product_id string, sequence int, side string, time datetime, trade_id int, type string, volume_24h decimal(20,8), volume_30d decimal(20,8))"
    depends_on:
      proton:
        condition: service_healthy


