version: "3"

services:
  proton-server:
    image: timeplus/proton:latest
    pull_policy: always
    ports:
      - "8123:8123" # HTTP
      - "9000:9000" # TCP
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - timeplus
    # `proton` depends on STREAM_STORAGE_BROKERS env variable
    # to discover stream store
    environment:
      - STREAM_STORAGE_BROKERS=stream-store:9092
    command: >
      /bin/bash -c "sleep 2; /entrypoint.sh"
    depends_on:
      - stream-store
    cap_add:
      - SYS_PTRACE

  stream-store:
    image: docker.vectorized.io/vectorized/redpanda:latest
    pull_policy: always
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - timeplus
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://stream-store:29092,OUTSIDE://stream-store:9092
      - --set
      - "redpanda.auto_create_topics_enabled=false"
      - --set
      - "redpanda.enable_idempotence=true"
      - --check=false
    container_name: redpanda-1

networks:
  timeplus:
    name: timeplus-net
