logger:
    # Possible levels [1]:
    # - none (turns off logging)
    # - fatal
    # - critical
    # - error
    # - warning
    # - notice
    # - information
    # - debug
    # - trace

    # [1]: https://github.com/pocoproject/poco/blob/poco-1.9.4-release/Foundation/include/Poco/Logger.h#L105-L114
    level: trace
    log: ./clickhouse-metastore/clickhouse-metastore.log
    errorlog: ./clickhouse-metastore/clickhouse-metastore.err.log
    # Rotation policy
    # See https://github.com/pocoproject/poco/blob/poco-1.9.4-release/Foundation/include/Poco/FileChannel.h#L54-L85
    size: 1000M
    count: 10
    # console: 1 
    # Default behavior is autodetection (log to console if not daemon mode and is tty)

max_connections: 4096

metastore_server:
    http_port: 9444

    # Must be unique among all keeper serves
    server_id: 1

    storage_path: ./metastore
    log_storage_path: ./metastore_log
    snapshot_storage_path: ./metastore_snapshot

    coordination_settings:
        operation_timeout_ms: 10000
        session_timeout_ms: 30000
        raft_logs_level: information
        # All settings listed in https://github.com/ClickHouse/ClickHouse/blob/master/src/Coordination/CoordinationSettings.h

    raft_configuration:
        server:
            id: 1
            # Internal port and hostname
            hostname: localhost
            port: 94444
        # Add more servers here

# Sources to read users, roles, access rights, profiles of settings, quotas.
user_directories:
    users_xml:
        # Path to configuration file with predefined users.
        path: users.yaml
    local_directory:
        # Path to folder where users created by SQL commands are stored.
        path: /var/lib/proton/access/

