name: UDFDockerImage

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      base_proton_tag:
        description: "Base Proton Docker Image Tag"
        default: "timeplus/proton:develop"
        required: true

      tag_suffix:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Proton UDF Docker Image Tag Suffix, e.g. timeplus/proton:proton_version-tag_suffix"
        # Default value if no value is explicitly provided
        default: "udf"
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: get proton versions
        run: |
          docker pull ${{ github.event.inputs.base_proton_tag }}
          docker run -d --name=proton-server --expose 8463 ${{ github.event.inputs.base_proton_tag }}
          containers=$(docker ps)
          echo $containers
          sleep 10s
          proton_ver=$(docker exec proton-server proton-client --query="select version()")
          echo "PROTON_VER=$proton_ver" >> $GITHUB_ENV
          



      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/udf
          build-args: BASE_TAG=${{ github.event.inputs.base_proton_tag }}
          push: true

          tags: timeplus/proton:${{ env.PROTON_VER }}-${{ github.event.inputs.tag_suffix }}

